version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && make test-coverage
      - coveralls/upload

workflows:
# Define your workflow here
  version: 2.1
  build-test:
    jobs:
      - build