version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      # Then run your tests and collect coverage!
      - run:
          name: Run tests with coverage
          command: mvn test jacoco:report

      - coveralls/upload

workflows:
# Define your workflow here
  version: 2.1
  build-test:
    jobs:
      - build